version: "2"
services:
  server:
    restart: always
    image: aiokinawa/traffic_signs:latest
    volumes:
      - ".:/app"
    ports:
      - "5000:5000"
    command: python ./scripts/run_server.py --config_path=./.config.yaml
