FROM aiokinawa/traffic_signs:001

LABEL name="aiokinawa/traffic_signs"
LABEL version="latest"

# Copy code and data
COPY . /app

# Set working directory to project's dir
WORKDIR /app

# Update conda environment
#RUN conda env update -f ./environment_linux.yaml
